//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaCorpSmartHome.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installations
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int InstallerId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string InstallerNotes { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
